services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game_php
    depends_on:
      - mysql  
    ports:
      - 80:80
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:latest
    container_name: game_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: game
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gamedemo_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8080:80


volumes:
  mysql_data:



